#!/usr/bin/env python3
"""
Embed a binary MicroRender pack into C.

The DOS runtime uses GAME.MRP from disk. The Pico/RP2350 build cannot rely on a
filesystem, so this converts the exact same generated GAME.MRP bytes into a C
translation unit. That makes DOS and Pico consume the same asset pack.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def c_ident(s: str) -> str:
    out = []
    for ch in s:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    name = "".join(out).strip("_") or "mr_embedded_assets"
    if name[0].isdigit():
        name = "_" + name
    return name


def emit_c(data: bytes, symbol: str, header_name: str, source_name: str) -> str:
    digest = hashlib.sha256(data).hexdigest()
    lines = []
    lines.append("/* Generated by shared/tools/mr_embed.py. Do not edit. */")
    lines.append(f"/* source: {source_name} */")
    lines.append(f"/* size: {len(data)} bytes */")
    lines.append(f"/* sha256: {digest} */")
    lines.append('#include <stddef.h>')
    lines.append('#include <stdint.h>')
    lines.append(f'#include "{header_name}"')
    lines.append("")
    lines.append(f"const uint8_t {symbol}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const size_t {symbol}_size = sizeof({symbol});")
    lines.append("")
    return "\n".join(lines)


def emit_h(symbol: str) -> str:
    guard = (symbol + "_H").upper()
    return f"""/* Generated by shared/tools/mr_embed.py. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>

extern const uint8_t {symbol}[];
extern const size_t {symbol}_size;

#endif /* {guard} */
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", "-i", required=True, help="Input .MRP file")
    ap.add_argument("--c", required=True, help="Output .c file")
    ap.add_argument("--h", required=True, help="Output .h file")
    ap.add_argument("--symbol", default="mr_embedded_assets")
    args = ap.parse_args()

    inp = Path(args.input)
    out_c = Path(args.c)
    out_h = Path(args.h)
    symbol = c_ident(args.symbol)

    data = inp.read_bytes()
    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_h.parent.mkdir(parents=True, exist_ok=True)

    header_name = out_h.name
    out_h.write_text(emit_h(symbol), encoding="utf-8", newline="\n")
    out_c.write_text(emit_c(data, symbol, header_name, inp.name), encoding="utf-8", newline="\n")

    print(f"embedded {inp} -> {out_c} / {out_h} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
